import React,{useState,useEffect,useMemo} from 'react';
import {Home,User,Search,MapPin,Clock,Check,Menu,Heart,Star} from 'lucide-react';
import {ImpactCarousel} from './components/ImpactCarousel.jsx';
import {MealCard} from './components/MealCard.jsx';
import {CookCard} from './components/CookCard.jsx';
import {Modal} from './components/Modal.jsx';
import {LocationPicker} from './components/LocationPicker.jsx';
import {InformationPage,informationPaths} from './pages/InformationPage.jsx';
import {listingDistance,distanceLabel,SEARCH_RADIUS_KM} from './lib/location.js';
import {PickupPicker} from './components/PickupPicker.jsx';
import {todayInPoland,addDays,dateLabel,hourLabel} from '../shared/dates.js';
import {filterMeals} from './lib/filterMeals.js';
const initialSearch={term:'',location:'Warsaw',postcode:'',coordinates:{lat:52.2297,lon:21.0122},date:null,time:'any'};
export default function App(){
 const path=window.location.pathname.replace(/\/$/,'')||'/';
 useEffect(()=>{const title=path==='/how-it-works'?'How it works':path==='/our-mission'?'Our mission':path==='/become-a-cook'?'Become a cook':null;document.title=title?`${title} | HomeChef`:'HomeChef | Home-cooked comfort, shared with purpose.';},[path]);
 const [catalog,setCatalog]=useState(null),[error,setError]=useState(false),[draft,setDraft]=useState(initialSearch),[search,setSearch]=useState(initialSearch),[filters,setFilters]=useState([]),[sort,setSort]=useState('recommended'),[saved,setSaved]=useState([]),[modal,setModal]=useState(null),[menu,setMenu]=useState(false);
 const load=()=>{setError(false);fetch('/api/catalog').then(r=>{if(!r.ok)throw Error();return r.json();}).then(setCatalog).catch(()=>setError(true));};
 useEffect(()=>{load();try{const stored=JSON.parse(localStorage.getItem('homechef-favourites')||'[]');if(Array.isArray(stored))setSaved(stored.filter(v=>typeof v==='string'));}catch{}},[]);
 const toggleSave=id=>setSaved(prev=>{const next=prev.includes(id)?prev.filter(v=>v!==id):[...prev,id];try{localStorage.setItem('homechef-favourites',JSON.stringify(next));}catch{}return next;});
 const results=useMemo(()=>catalog?filterMeals(catalog.meals,search,filters,sort):[],[catalog,search,filters,sort]);
 const openInfo=type=>{setMenu(false);setModal({type});};
 const explore=e=>{e.preventDefault();setSearch({...draft});document.getElementById('meals').scrollIntoView({behavior:'smooth',block:'start'});};
 const reset=()=>{const next={...search,term:'',date:null,time:'any'};setFilters([]);setDraft(next);setSearch(next);setSort('recommended');};
 return <><header className="header"><a className="brand" href="/" aria-label="HomeChef home"><span className="brand-symbol"><Home size={19}/></span><span>HomeChef</span></a><nav aria-label="Main navigation" className={menu?'nav mobile-open':'nav'}><a href="/how-it-works" aria-current={path==='/how-it-works'?'page':undefined}>How it works</a><a href="/our-mission" aria-current={path==='/our-mission'?'page':undefined}>Our mission</a><a href="/become-a-cook" aria-current={path==='/become-a-cook'?'page':undefined}>Become a cook</a></nav><div className="header-actions"><button className="profile" onClick={()=>openInfo('profile')}><User size={18}/><span>Profile</span></button><button className="menu-toggle icon-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu size={22}/></button></div></header>
 {informationPaths.includes(path)?<InformationPage path={path}/>:<main><section className="hero"><div className="hero-circle circle-one"/><div className="hero-circle circle-two"/><div className="hero-banner"><div className="hero-copy"><h1>Home-cooked comfort, <span>shared with purpose.</span></h1><h2 className="hero-description">Discover the comfort of homemade meals prepared by cooks in your community.</h2><h2 className="hero-purpose"><strong>Every meal you order directly supports local women building financial independence through their culinary talent.</strong></h2></div><div className="hero-visual"><img src="/images/homechef-hero.png" alt="A smiling home cook preparing a meal in a warm home kitchen" fetchPriority="high" width="1402" height="768"/></div></div><form className="search-bar" onSubmit={explore}><label className="search-field"><Search size={19}/><span className="sr-only">Search meals or cuisines</span><input type="search" placeholder="Try pierogi, pasta, or a cuisine" value={draft.term} onChange={e=>setDraft({...draft,term:e.target.value})}/></label><div className="select-field location-field"><LocationPicker value={draft} onChange={selection=>setDraft({...draft,...selection})}/></div><div className="select-field time-field"><PickupPicker value={draft} onChange={selection=>{setDraft({...draft,...selection});if(!selection.date)setSearch(prev=>({...prev,date:null,time:'any'}));}}/></div><button className="primary" type="submit">Explore meals</button></form><p className="availability-note"><span><Check size={12}/></span>{draft.date?'We’ll only show meals that cooks can prepare for your selected place and time.':'Explore meals nearby, or choose a date and time to narrow your search.'}</p></section>
 <section className="cooks-section"><div className="container"><div className="local-heading"><h2>Meet our new chefs</h2><span>Meet the people behind your next meal.</span></div><div className="cook-grid">{catalog?.cooks.filter(c=>listingDistance(c,search)<=SEARCH_RADIUS_KM).map(c=><CookCard key={c.id} cook={c} search={search} location={search.location} onOpen={()=>setModal({type:'cook',cook:c})}/>)}</div></div></section>
 <section id="meals" className="meals-section container"><div className="section-top"><div><h2>Meals near {search.location}</h2><p className="results-count" aria-live="polite">{catalog?`${results.length} home-cooked ${results.length===1?'meal':'meals'} available`:error?'Meals are taking a little longer to load.':'Finding your next homemade meal…'}</p></div><label className="sort-control"><span className="sr-only">Sort meals</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="price">Price: low to high</option><option value="rating">Top rated</option><option value="distance">Nearest pickup</option></select></label></div><p className="selected-schedule">{search.date?`Pickup ${dateLabel(search.date)}${search.time!=='any'?` at ${hourLabel(Number(search.time))}`:' · any available time'}`:'All pickup dates and times'} · within 15 km</p><div className="filters" aria-label="Filter meals">{['Vegetarian','Under 30 zł','Top rated','Pickup'].map(f=><button key={f} className={`chip ${filters.includes(f)?'active':''}`} aria-pressed={filters.includes(f)} onClick={()=>setFilters(prev=>prev.includes(f)?prev.filter(v=>v!==f):[...prev,f])}>{f}</button>)}{(filters.length>0||search.term||search.time!=='any'||search.date!==initialSearch.date)&&<button className="clear-filters" onClick={reset}>Clear filters</button>}</div>
 {error?<div className="empty-state"><h3>We couldn’t load the meals.</h3><p>Please try again in a moment.</p><button className="primary" onClick={load}>Try again</button></div>:!catalog?<div className="meal-grid skeleton-grid" aria-label="Loading meals">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div>:results.length?<div className="meal-grid">{results.map(m=><MealCard key={m.id} meal={m} date={search.date} search={search} location={search.location} saved={saved.includes(m.id)} onSave={()=>toggleSave(m.id)} onOpen={()=>setModal({type:'meal',meal:m})}/>)}</div>:<div className="empty-state"><Search size={26}/><h3>No meals match just yet.</h3><p>Try another address, cuisine, pickup time, or filter. Sample meals are currently listed around Warsaw, Kraków, and Wrocław.</p><button className="primary" onClick={reset}>Clear meal filters</button></div>}
 </section></main>}{path==='/'&&<ImpactCarousel/>}<footer className="footer container"><span>HomeChef</span><p>Made at home. Shared with community.</p><span className="demo-label">Demo · Sample meals & cooks</span></footer>
 {modal&&<Modal title={modal.type==='meal'?modal.meal.name:modal.type==='cook'?modal.cook.name:modal.type==='how'?'A homemade meal, close to you.':modal.type==='mission'?'Every kitchen holds a possibility.':modal.type==='partner'?'Your cooking. Your opportunity.':'Your favourites'} onClose={()=>setModal(null)}>
 {modal.type==='profile'&&<><p className="modal-note">Your saved meals stay on this device. Accounts and ordering are coming later.</p>{catalog?.meals.filter(m=>saved.includes(m.id)).length?<div className="saved-list">{catalog.meals.filter(m=>saved.includes(m.id)).map(m=><div key={m.id}><img src={m.image} alt=""/><button onClick={()=>setModal({type:'meal',meal:m})}>{m.name}<span>{m.price} zł · {m.kitchen}</span></button><button className="icon-button" aria-label={`Remove ${m.name} from favourites`} onClick={()=>toggleSave(m.id)}><Heart size={20} fill="currentColor"/></button></div>)}</div>:<p>Tap a heart on a meal to save it here.</p>}</>}
 {modal.type==='meal'&&<><img className="detail-image" src={modal.meal.image} alt={modal.meal.name}/><div className="detail-title"><strong>{modal.meal.price} zł</strong><span><Star size={15} fill="currentColor"/> {modal.meal.rating} ({modal.meal.reviews} reviews)</span></div><p>{modal.meal.description}</p><p><strong>{modal.meal.kitchen}</strong><br/>Pickup {dateLabel(search.date||modal.meal.availableDates.find(d=>d>todayInPoland())||modal.meal.availableDates[0])} · {modal.meal.time}<br/>{modal.meal.area} · {distanceLabel(modal.meal,search)} away</p><p className="modal-note">Sample listing. Ordering and payments will be added later.</p><button className="primary" onClick={()=>toggleSave(modal.meal.id)}>{saved.includes(modal.meal.id)?'Remove from favourites':'Save meal'}</button></>}
 {modal.type==='cook'&&<><div className="cook-detail"><img src={modal.cook.image} alt={`Cook at ${modal.cook.name}`}/><div><p>{modal.cook.speciality}</p><p>{modal.cook.rating} ★ · {modal.cook.area}</p></div></div><div className="cook-about"><h3>About the cook</h3><p>“{modal.cook.story}”</p></div><button className="primary" onClick={()=>{const next={...initialSearch,location:search.location,coordinates:search.coordinates,postcode:search.postcode,date:search.date,time:search.time,term:modal.cook.name};setDraft(next);setSearch(next);setFilters([]);setModal(null);document.getElementById('meals').scrollIntoView({behavior:'smooth'});}}>Explore this kitchen</button></>}
 </Modal>}</>;
}
