import React,{useState,useRef,useEffect} from 'react';
import {MapPin,Search,ChevronRight} from 'lucide-react';
import {Modal} from './Modal.jsx';
export function LocationPicker({value,onChange}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const input=useRef(null),controller=useRef(null);
 useEffect(()=>{if(open)input.current?.focus();return ()=>controller.current?.abort();},[open]);
 const run=async()=>{if(busy||query.trim().length<2)return;setBusy(true);setError('');setResults(null);controller.current?.abort();const c=new AbortController();controller.current=c;try{const r=await fetch(`/api/locations?q=${encodeURIComponent(query.trim())}`,{signal:c.signal});const data=await r.json();if(!r.ok)throw Error(data.error||'Address search is unavailable.');setResults(data.results);}catch(e){if(e.name!=='AbortError')setError(e.message);}finally{if(!c.signal.aborted)setBusy(false);}};
 return <><button type="button" className="location-trigger" aria-haspopup="dialog" onClick={()=>{setOpen(true);setBusy(false);setError('');setResults(null);}}><MapPin size={20}/><span>{value.location}<small>{value.postcode||'Street, postcode, or city'}</small></span><ChevronRight size={15}/></button>{open&&<Modal title="Where would you like to pick up?" onClose={()=>setOpen(false)}><label className="address-label" htmlFor="address-query">Street, postcode, or city in Poland</label><div className="address-search"><input id="address-query" ref={input} type="search" maxLength={160} value={query} placeholder="e.g. Marszałkowska, Warszawa or 00-001" onChange={e=>{setQuery(e.target.value);setError('');setResults(null);}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();run();}}}/><button type="button" className="primary" disabled={busy||query.trim().length<2} onClick={run}>{busy?'Searching…':'Search'}</button></div><p className="address-help">Include the city when searching for a street. Postcodes can be entered on their own.</p><div aria-live="polite">{error&&<p className="address-error" role="alert">{error}</p>}{results?.length===0&&<p>No matching location found in Poland. Try adding a city or check the postcode.</p>}{results?.length>0&&<div className="address-results">{results.map(r=><button type="button" key={r.id} onClick={()=>{onChange({location:r.label,postcode:r.postcode,coordinates:{lat:r.lat,lon:r.lon}});setOpen(false);}}><MapPin size={18}/><span><strong>{r.label}</strong><small>{r.detail}</small></span><ChevronRight size={16}/></button>)}</div>}</div><p className="address-attribution">Location data © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a></p></Modal>}</>;
}
